defaultBaseImage: cgr.dev/chainguard/static:latest
builds:
  - id: homerun2-omni-pitcher
    main: .
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Env.VERSION}}
      - -X main.commit={{.Env.COMMIT}}
      - -X main.date={{.Env.DATE}}
