apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homerun2

resources:
- serviceaccount.yaml
- configmap.yaml
- secret-token.yaml
- secret-redis.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: homerun2

images:
- name: homerun2-omni-pitcher
  newName: ghcr.io/stuttgart-things/homerun2-omni-pitcher/homerun2-omni-pitcher-19372b3164b7560205efc0b3c53f43c1
  digest: sha256:a5a828d899040e57f116375922f376e73decdc86302e3a9f375077b64d66b711
