apiVersion: v1
kind: Secret
metadata:
  name: homerun2-omni-pitcher-redis
  labels:
    app: homerun2-omni-pitcher
    app.kubernetes.io/name: homerun2-omni-pitcher
    app.kubernetes.io/component: api
type: Opaque
stringData:
  # Redis connection details for homerun2 namespace
  address: "redis-stack.homerun2.svc.cluster.local:6379"
  password: "Atlan7is2026" # pragma: allowlist secret
