apiVersion: v1
kind: ServiceAccount
metadata:
  name: homerun2-omni-pitcher
  labels:
    app: homerun2-omni-pitcher
    app.kubernetes.io/name: homerun2-omni-pitcher
    app.kubernetes.io/component: api
automountServiceAccountToken: false
